name: Publish

on: [push, pull_request]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker run --rm -v $PWD:/workdir:z ivanpondal/alpine-latex pdflatex resume.tex
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./resume.pdf
        asset_name: resume.pdf
        asset_content_type: application/pdf
        tag: latest
        overwrite: true
